# Generated by Django 5.2.1 on 2025-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/pics')),
                ('disponibilité', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
