# Generated by Django 5.2.1 on 2025-05-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
    ]
