# Generated by Django 5.2.1 on 2025-05-28 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('avis', models.TextField()),
                ('image', models.ImageField(upload_to='media/pics')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=40)),
                ('Date_Check_In', models.DateField()),
                ('Date_Check_Out', models.DateField()),
                ('Note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('places', models.PositiveIntegerField(default=1)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.chambre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
