# Generated by Django 5.2.1 on 2025-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
